version: 0.0
os: linux

files:
  - source: scripts
    destination: /opt/ec2-demo/scripts
  - source: deploy
    destination: /opt/ec2-demo/deploy
  - source: docker-compose.yml
    destination: /opt/ec2-demo

permissions:
  - object: /opt/ec2-demo
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user