version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: ec2-demo-app
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION}
      - ECR_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}
      # Use the full commit SHA as the immutable tag (already good practice)
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
  build:
    commands:
      - echo Build JAR & Docker image
      # If your EC2 is x86, make sure you push an amd64 image from Mac builders; on CodeBuild x86 you can keep plain build
      # - docker buildx create --use --name multi || docker buildx use multi
      # - docker buildx build --platform linux/amd64 -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ECR_URI}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${ECR_URI}/${IMAGE_REPO_NAME}:latest
  post_build:
    commands:
      - echo Pushing images...
      - docker push ${ECR_URI}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - docker push ${ECR_URI}/${IMAGE_REPO_NAME}:latest
      # Write immutable tag for Deploy stage to consume (unchanged, but move to deploy/ is nicer)
      - mkdir -p deploy
      - echo ${IMAGE_TAG} > deploy/image_tag.txt
      # Also write the image digest so you can pin-by-digest if desired
      - DIGEST=$(aws ecr describe-images --repository-name ${IMAGE_REPO_NAME} --image-ids imageTag=${IMAGE_TAG} --region ${REGION} --query 'imageDetails[0].imageDigest' --output text)
      - echo ${DIGEST} > deploy/image_digest.txt
      - printf '{"image":"%s","tag":"%s","digest":"%s","ecr_uri":"%s"}' "${IMAGE_REPO_NAME}" "${IMAGE_TAG}" "${DIGEST}" "${ECR_URI}" > deploy/image_detail.json
artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - scripts/**/*
    - deploy/image_tag.txt
    - deploy/image_digest.txt
    - deploy/image_detail.json