version: "3.9"

services:
  app:
    image: "${ECR_URI:-ec2-demo-app}:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-local}"
